name: Tests

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - nightly
  #     - main
  #     - master
  #   tags:
  #     # Release candidate tags look like: v1.11.0-rc1
  #     - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: |
        sudo apt-get install libsystemd-dev
        tox
